apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master-replica
  namespace: redis-cluster
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.0
        command:
          - "redis-server"
          - "/config/redis.conf"
          - "--slaveof"
          - "redis-master.redis-cluster.svc.cluster.local"
          - "6379"
        volumeMounts:
        - name: redis-config
          mountPath: /config
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
          items:
            - key: redis.conf
              path: redis.conf
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

